---
- name: include {{ role }} variables
  include_vars:
    file: group_vars/{{ role }}

- name: include {{ role }} tasks
  include_tasks: "{{ dba_tasks }}"
  loop:
    - users.yml
    - sudoers.yml
    - packages.yml
    - limits.yml
  loop_control:
    loop_var: dba_tasks

- name: include {{ role }} specific Environment playbooks
  include_tasks: "{{ env_zone }}"
  loop:
    - "{{ env }}.yml"
    - "{{ zone }}.yml"
  loop_control:
    loop_var: env_zone